### ISSUE TITLE
Sugestão: Opção darkmode

### ISSUE THREAD

**Issue by paulo-santana** [ronaldinhojatasolto/ronaldinhojatasolto.github.io#3]
Olá, gostei muito do projeto, porém creio que pode gerar desconforto visual pra alguns usuários. Como já é uma tendência e várias empresas já estão adotando, sugiro adicionar um modo dark pra diminuir o cansaço dos olhos.

Eu apenas não sei como fazer isso sem CSS ou javascript, então se virem aí. Obrigado desde já

**Comment by OtacilioN** [comment]
Excelente sugestão, pull requests nesse sentido são bem vindas.

**Comment by OtacilioN** [comment]
Dark Mode implementado por @gabriias no PR #6 

Obrigado por contribuirem @gabriias @paulo-santana

**Comment by paulo-santana** [comment]
Gratidão 🙏
